//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorkDB.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_WORKDB_DIALOG               102
#define IDD_WORKDB_EXPORT               103
#define CG_IDD_PROGRESS                 104
#define CG_IDS_PROGRESS_CAPTION         105
#define IDD_LISTSETUP                   108
#define IDD_PRINT_STATUS                110
#define IDR_MAINFRAME                   128
#define IDD_SRCDB_ADD                   129
#define IDD_OPTIONS_DIALOG              130
#define IDD_WORKDB_STAFF                131
#define IDD_ATTRIBUTE_ADD               132
#define IDD_WORKDB_IMPORT               133
#define IDD_QUERY                       134
#define IDD_WORKDB_VERIFY               135
#define IDD_DATA_TEXT                   136
#define IDD_DATA_DATUM                  137
#define IDD_DATA_NAMES                  138
#define IDD_DATA_DATUM_INTERVALLUM      139
#define IDD_DATA_DICT_STRONG            140
#define IDD_DATA_DICT_APPEND            141
#define IDD_RESULT                      142
#define IDD_DATA_SEL                    143
#define IDR_PRINT                       143
#define IDD_OPTIONS_VER                 144
#define IDD_RESULT_OPTION               145
#define IDD_TXT_IMPORT                  147
#define IDD_SELDBTOBIN                  148
#define IDC_BUTTON_EXPORT               1000
#define IDC_LIST_PERSON                 1000
#define IDC_BUTTON_IMPORT               1001
#define IDC_LIST1                       1001
#define IDC_LIST_SELECTED               1001
#define IDC_BUTTON_ADD_PERSON           1001
#define IDC_BUTTON_BIN                  1002
#define IDC_BUTTON_ADD                  1002
#define IDC_BUTTON_MOD_PERSON           1002
#define IDC_BUTTON_FTP                  1003
#define IDC_BUTTON_MOD                  1003
#define IDC_EDIT1                       1003
#define IDC_BUTTON_DEL_PERSON           1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_BUTTON_DEL                  1004
#define IDC_BUTTON_DATATYPE             1004
#define IDC_BUTTON_UPDATE               1004
#define IDC_BUTTON_OPTIONS              1004
#define IDC_EDIT2                       1004
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_BUTTON_TXT                  1004
#define IDC_BUTTON_DEL_ATTR             1005
#define IDC_TREE1                       1005
#define IDC_EDIT3                       1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_BUTTON_ADD_ATTR             1006
#define IDC_EDIT4                       1006
#define IDC_BUTTON_UP                   1007
#define IDC_EDIT5                       1007
#define IDC_BUTTON_DOWN                 1008
#define IDC_STATIC_MSG                  1008
#define IDC_EDIT6                       1008
#define IDC_COMBO1                      1009
#define IDC_EDIT_DIR                    1009
#define IDC_LIST_ALL                    1010
#define IDC_BUTTON_DATA_ADD             1010
#define IDC_COMBO2                      1010
#define IDC_BUTTON_DATA_MOD             1011
#define IDC_STATIC_TITLE                1011
#define IDC_COMBO3                      1011
#define IDC_BUTTON_DATA_DEL             1012
#define IDC_CHECK1                      1012
#define IDC_CHECK2                      1013
#define IDC_CHECK3                      1014
#define IDC_CHECK4                      1015
#define IDC_CHECK5                      1016
#define IDC_CHECK6                      1017
#define IDC_COMBO4                      1018
#define IDC_LIST_ATTRIBS                1019
#define IDC_EDIT7                       1019
#define IDC_EDIT8                       1020
#define IDC_PROGRESS1                   1020
#define IDC_EDIT9                       1021
#define IDC_EDIT10                      1022
#define IDC_COMBO5                      1023
#define IDC_EDIT11                      1024
#define IDC_EDIT12                      1025
#define IDC_EDIT13                      1026
#define IDC_EDIT14                      1027
#define IDC_EDIT15                      1028
#define IDC_EDIT16                      1029
#define IDC_COMBO6                      1030
#define IDC_EDIT17                      1031
#define IDC_BT_PRINTOPT                 1031
#define IDC_EDIT18                      1032
#define IDC_EDIT19                      1033
#define IDC_EDIT20                      1034
#define IDC_EDIT21                      1035
#define IDC_EDIT22                      1036
#define IDC_COMBO7                      1037
#define IDC_EDIT23                      1038
#define IDC_BUTTON1                     1039
#define IDC_BUTTON2                     1040
#define IDC_BUTTON_SAVE                 1041
#define IDC_SPIN1                       1041
#define IDC_BUTTON_CLIPBOARD            1042
#define IDC_RADIO1                      1042
#define IDC_RADIO2                      1043
#define IDC_BUTTON_FORRAS_ALL           1043
#define IDC_BUTTON_PRINT                1043
#define IDC_BUTTON_FORRAS_MONE          1044
#define IDC_BUTTON_COLUMN               1044
#define IDC_SPIN2                       1045
#define IDC_LIST2                       1045
#define IDC_LIST3                       1046
#define IDC_BUTTON_BIND                 1047
#define IDC_ED_MMSX                     1048
#define IDC_STATIC_REPORT               1049
#define IDC_SPIN3                       1050
#define IDC_COMBO_TEXT1                 1050
#define IDC_COMBO_TEXT2                 1051
#define IDC_COMBO_TEXT3                 1052
#define IDC_ED_MMDOWN                   1057
#define IDC_SPIN4                       1058
#define IDC_ED_MMUP                     1061
#define IDC_ED_MMDX                     1063
#define IDC_ANIMATE1                    1067
#define IDC_PC                          1071
#define IDC_TEXT1                       1072
#define IDC_PAGES                       1073
#define IDC_EDFOOTER                    1074
#define IDC_CBFHEAD                     1075
#define IDC_CBSHEAD                     1076
#define IDC_CBFFOOTER                   1077
#define IDC_CBSFOOTER                   1078
#define IDC_CBFCORPO                    1079
#define IDC_CBSCORPO                    1080
#define IDC_EDHEAD                      1081
#define IDC_EDPAGE                      1082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
